// Code generated by goctl. DO NOT EDIT!
// Source: account.proto

package accountservice

import "errors"

var errJsonConvert = errors.New("json convert error")

type (
	Account struct {
		Uuid               string `json:"uuid,omitempty"`
		Name               string `json:"name,omitempty"`
		Email              string `json:"email,omitempty"`
		PhoneNumber        string `json:"phone_number,omitempty"`
		ProtoUrl           string `json:"proto_url,omitempty"`
		ConfirmedAndActive bool   `json:"confirmedAndActive,omitempty"`
		Support            bool   `json:"support,omitempty"`
		MemberSince        int64  `json:"memberSince,omitempty"`
	}

	AccountEmpty struct {
	}

	AccountList struct {
		Accounts []*Account `json:"accounts,omitempty"`
		Limit    int32      `json:"limit,omitempty"`
		Offset   int32      `json:"offset,omitempty"`
	}

	CreateAccountRequest struct {
		Name        string `json:"name,omitempty"`
		Email       string `json:"email,omitempty"`
		PhoneNumber string `json:"phone_number,omitempty"`
	}

	EmailChangeRequest struct {
		Uuid  string `json:"uuid,omitempty"`
		Email string `json:"email,omitempty"`
	}

	EmailConfirmation struct {
		Uuid  string `json:"uuid,omitempty"`
		Email string `json:"email,omitempty"`
	}

	GetAccountByEmailRequest struct {
		Email string `json:"email,omitempty"`
	}

	GetAccountByPhoneNumberRequest struct {
		PhoneNumber string `json:"phone_number,omitempty"`
	}

	GetAccountListRequest struct {
		Limit  int32 `json:"limit,omitempty"`
		Offset int32 `json:"offset,omitempty"`
	}

	GetAccountRequest struct {
		Uuid string `json:"uuid,omitempty"`
	}

	GetOrCreateRequest struct {
		Name        string `json:"name,omitempty"`
		Email       string `json:"email,omitempty"`
		PhoneNumber string `json:"phone_number,omitempty"`
	}

	PasswordResetRequest struct {
		Email string `json:"email,omitempty"`
	}

	SyncUserRequest struct {
		Uuid string `json:"uuid,omitempty"`
	}

	TrackEventRequest struct {
		Uuid  string `json:"uuid,omitempty"`
		Event string `json:"event,omitempty"`
	}

	UpdatePasswordRequest struct {
		Uuid     string `json:"uuid,omitempty"`
		Password string `json:"password,omitempty"`
	}

	VerifyPasswordRequest struct {
		Email    string `json:"email,omitempty"`
		Password string `json:"password,omitempty"`
	}
)
